kumuluzee:
  name: ms-event
  version: 1.0
  server:
    base-url: http://127.0.0.1:8082
    http:
      port: 8082
      
  datasources:
    - jndi-name: jdbc/ms-eventDS
      connection-url: jdbc:mysql://localhost:3306/db-assistance-event?useSSL=false
      username: root
      password: admin
      max-pool-size: 20      
  swagger:
    base-url: http://localhost:8082/v1/
    enabled: true
    ui:
      enabled: true