kumuluzee:
  name: ms-person
  version: 1.0
  server:
    base-url: http://127.0.0.1:8081
    http:
      port: 8080
      
  datasources:
    - jndi-name: jdbc/ms-personDS
      connection-url: jdbc:mysql://localhost:3306/db-assistance-person?useSSL=false
      username: root
      password: admin
      max-pool-size: 20      
  swagger:
    base-url: http://localhost:8081/v1/
    enabled: true
    ui:
      enabled: true