
package com.tharsis.info.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "usuario", targetNamespace = "http://services.academico.ulasalle.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Usuario {


    /**
     * 
     * @param password
     * @param dni
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "sesionValidaReturn", targetNamespace = "http://services.academico.ulasalle.com")
    @RequestWrapper(localName = "sesionValida", targetNamespace = "http://services.academico.ulasalle.com", className = "com.tharsis.info.service.SesionValida")
    @ResponseWrapper(localName = "sesionValidaResponse", targetNamespace = "http://services.academico.ulasalle.com", className = "com.tharsis.info.service.SesionValidaResponse")
    public boolean sesionValida(
        @WebParam(name = "dni", targetNamespace = "http://services.academico.ulasalle.com")
        String dni,
        @WebParam(name = "password", targetNamespace = "http://services.academico.ulasalle.com")
        String password);

    /**
     * 
     * @param dni
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getInformacionReturn", targetNamespace = "http://services.academico.ulasalle.com")
    @RequestWrapper(localName = "getInformacion", targetNamespace = "http://services.academico.ulasalle.com", className = "com.tharsis.info.service.GetInformacion")
    @ResponseWrapper(localName = "getInformacionResponse", targetNamespace = "http://services.academico.ulasalle.com", className = "com.tharsis.info.service.GetInformacionResponse")
    public String getInformacion(
        @WebParam(name = "dni", targetNamespace = "http://services.academico.ulasalle.com")
        String dni);

    /**
     * 
     * @param dni
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getPeriodosReturn", targetNamespace = "http://services.academico.ulasalle.com")
    @RequestWrapper(localName = "getPeriodos", targetNamespace = "http://services.academico.ulasalle.com", className = "com.tharsis.info.service.GetPeriodos")
    @ResponseWrapper(localName = "getPeriodosResponse", targetNamespace = "http://services.academico.ulasalle.com", className = "com.tharsis.info.service.GetPeriodosResponse")
    public String getPeriodos(
        @WebParam(name = "dni", targetNamespace = "http://services.academico.ulasalle.com")
        String dni);

    /**
     * 
     * @param nuevaContrasena
     * @param contrasena
     * @param dni
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "setContrasenaReturn", targetNamespace = "http://services.academico.ulasalle.com")
    @RequestWrapper(localName = "setContrasena", targetNamespace = "http://services.academico.ulasalle.com", className = "com.tharsis.info.service.SetContrasena")
    @ResponseWrapper(localName = "setContrasenaResponse", targetNamespace = "http://services.academico.ulasalle.com", className = "com.tharsis.info.service.SetContrasenaResponse")
    public String setContrasena(
        @WebParam(name = "dni", targetNamespace = "http://services.academico.ulasalle.com")
        String dni,
        @WebParam(name = "contrasena", targetNamespace = "http://services.academico.ulasalle.com")
        String contrasena,
        @WebParam(name = "nuevaContrasena", targetNamespace = "http://services.academico.ulasalle.com")
        String nuevaContrasena);

    /**
     * 
     * @param navegador
     * @param password
     * @param ubicacion
     * @param firebaseid
     * @param ip
     * @param dni
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sesionValidaFirebaseReturn", targetNamespace = "http://services.academico.ulasalle.com")
    @RequestWrapper(localName = "sesionValidaFirebase", targetNamespace = "http://services.academico.ulasalle.com", className = "com.tharsis.info.service.SesionValidaFirebase")
    @ResponseWrapper(localName = "sesionValidaFirebaseResponse", targetNamespace = "http://services.academico.ulasalle.com", className = "com.tharsis.info.service.SesionValidaFirebaseResponse")
    public String sesionValidaFirebase(
        @WebParam(name = "dni", targetNamespace = "http://services.academico.ulasalle.com")
        String dni,
        @WebParam(name = "password", targetNamespace = "http://services.academico.ulasalle.com")
        String password,
        @WebParam(name = "navegador", targetNamespace = "http://services.academico.ulasalle.com")
        String navegador,
        @WebParam(name = "ip", targetNamespace = "http://services.academico.ulasalle.com")
        String ip,
        @WebParam(name = "ubicacion", targetNamespace = "http://services.academico.ulasalle.com")
        String ubicacion,
        @WebParam(name = "firebaseid", targetNamespace = "http://services.academico.ulasalle.com")
        String firebaseid);

    /**
     * 
     * @param firebaseid
     * @param dni
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CerrarSesionFirebase")
    @WebResult(name = "CerrarSesionFirebaseReturn", targetNamespace = "http://services.academico.ulasalle.com")
    @RequestWrapper(localName = "CerrarSesionFirebase", targetNamespace = "http://services.academico.ulasalle.com", className = "com.tharsis.info.service.CerrarSesionFirebase")
    @ResponseWrapper(localName = "CerrarSesionFirebaseResponse", targetNamespace = "http://services.academico.ulasalle.com", className = "com.tharsis.info.service.CerrarSesionFirebaseResponse")
    public String cerrarSesionFirebase(
        @WebParam(name = "dni", targetNamespace = "http://services.academico.ulasalle.com")
        String dni,
        @WebParam(name = "firebaseid", targetNamespace = "http://services.academico.ulasalle.com")
        String firebaseid);

    /**
     * 
     * @param navegador
     * @param nuevaContrasena
     * @param ubicacion
     * @param firebaseid
     * @param ip
     * @param contrasena
     * @param dni
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "setContrasenav2Return", targetNamespace = "http://services.academico.ulasalle.com")
    @RequestWrapper(localName = "setContrasenav2", targetNamespace = "http://services.academico.ulasalle.com", className = "com.tharsis.info.service.SetContrasenav2")
    @ResponseWrapper(localName = "setContrasenav2Response", targetNamespace = "http://services.academico.ulasalle.com", className = "com.tharsis.info.service.SetContrasenav2Response")
    public String setContrasenav2(
        @WebParam(name = "dni", targetNamespace = "http://services.academico.ulasalle.com")
        String dni,
        @WebParam(name = "contrasena", targetNamespace = "http://services.academico.ulasalle.com")
        String contrasena,
        @WebParam(name = "nuevaContrasena", targetNamespace = "http://services.academico.ulasalle.com")
        String nuevaContrasena,
        @WebParam(name = "navegador", targetNamespace = "http://services.academico.ulasalle.com")
        String navegador,
        @WebParam(name = "ip", targetNamespace = "http://services.academico.ulasalle.com")
        String ip,
        @WebParam(name = "ubicacion", targetNamespace = "http://services.academico.ulasalle.com")
        String ubicacion,
        @WebParam(name = "firebaseid", targetNamespace = "http://services.academico.ulasalle.com")
        String firebaseid);

}
